name: Run Academic Watch Daily

on:
  schedule:
    - cron: '0 8 * * *'  # Exécute tous les jours à 08:00 UTC
  workflow_dispatch:

jobs:
  run-academic-watch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Academic Watch
      env:
        GITHUB_ACTIONS: true
      run: |
        python src/main.py
